#!/bin/bash
set -e
# This is a simple script to create user services with full privileges.
# Be careful!.

# RAND=`strings /dev/urandom | grep -o '[[:alnum:]]' | head -n 30 | tr -d '\n'; echo`
RAND=`tr -dc A-Za-z0-9 </dev/urandom | head -c 35 ; echo ''`

DBNAME=${1:-my_pg_user}
DBUSER=${2:-my_awesome_db}
DBUSER_PASS=${3:-$RAND}

# Docker creation
psql -U postgres -c "CREATE DATABASE $DBNAME WITH ENCODING 'UTF8'"
psql -U postgres -c "create user $DBUSER with encrypted password '$DBUSER_PASS'"
psql -U postgres -c "grant all privileges on database $DBNAME to $DBUSER;"


echo $DBUSER_PASS
